/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-05-07 09:23:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


       response.setHeader("Cache-Control","no-cache,no-store,must-revalidate");//HTTP 1.1
       response.setHeader("Pragma","no-cache"); //HTTP 1.0
       response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

              System.out.println("\nLogin.jsp");
              
              System.out.println("Attribute ID : "+request.getSession().getAttribute("Id"));
              System.out.println("Parameter Username : "+request.getParameter("username"));

              if(request.getParameter("username") == null && request.getSession().getAttribute("Id")!=null && request.getSession().getAttribute("Logged")!="false")
              {
                     
                     System.out.println("Backed while logged in");
                     request.getSession().setAttribute("Id",null);
              request.getSession().setAttribute("Logged", "false");
               response.sendRedirect("Login.jsp");
                     return;
                
              }

              if(request.getSession().getAttribute("Id")!="-2" && request.getSession().getAttribute("Logged")=="false")
              {
                     System.out.println("Changing Logged");
                     request.getSession().setAttribute("Id","-1");
                     System.out.println("Attribute ID : "+request.getSession().getAttribute("Id"));
                     System.out.println("Parameter Username : "+request.getParameter("username"));
                     
              }


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"icon\" href=\"Capture5.png\" type=\"image/gif\" sizes=\"70x70\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("        <link rel='shortcut icon' type='image/x-icon' href='favicon.ico'/>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Login</title>\r\n");
      out.write("       <!--  <script type=\"text/javascript\" src=\"vehicleregis.js\"></script> -->\r\n");
      out.write("        <link rel='stylesheet' type=\"text/css\" href=\"Login.css\">\r\n");
      out.write("\t\t<link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    \r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"w3-bar w3-white w3-card\" id=\"myNavbar\">\r\n");
      out.write("    \r\n");
      out.write("<a href=\"#home\" class=\"w3-bar-item w3-button w3-wide\">\r\n");
      out.write("        \r\n");
      out.write("<div class=\"logo-image\">\r\n");
      out.write("            \r\n");
      out.write("<img src=\"Capture1.PNG\" >\r\n");
      out.write("      \r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</a>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"w3-right w3-hide-small\">\r\n");
      out.write("      \r\n");
      out.write("<a href=\"h1.html\" class=\"w3-bar-item w3-button\">HOME</a>\r\n");
      out.write("      \r\n");
      out.write("<a href=\"aboutus.html\" class=\"w3-bar-item w3-button\">ABOUT US</a>\r\n");
      out.write("     \r\n");
      out.write("<a href=\"contactus.html\" class=\"w3-bar-item w3-button\">CONTACT US</a>\r\n");
      out.write("      \r\n");
      out.write("<a href=\"Login.html\" class=\"w3-bar-item w3-button\">LOGIN</a>\r\n");
      out.write("      \r\n");
      out.write("<!--<a href=\"#contact\" class=\"w3-bar-item w3-button\">\r\n");
      out.write("<i class=\"fa fa-envelope\"></i> CONTACT</a>-->\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("        <br />    <br />    <br />    <br />    <br />\r\n");
      out.write("                <div class=\"registration\"><br>\r\n");
      out.write("\r\n");
      out.write("                    <form  align=\"left\" action=\"LoginUser\" method=\"Post\">\r\n");
      out.write("                    <br><h1 align=\"center\">Login<br></h1><br><br />\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"number\">1</span> Username\r\n");
      out.write("                    <input type=\"text\" name=\"empid\" placeholder=\"Enter your Employee Id\" required> \r\n");
      out.write("                    <label id=\"lvehicleno\" style=\"color:grey; visibility:visible\">Max 10 characters</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"number\">2</span> Password\r\n");
      out.write("                    <input type=\"password\" name=\"password\" placeholder=\"Enter your password\" required> \r\n");
      out.write("                    <label id=\"lpassword\" style=\"color:grey; visibility:visible\">Please use alphanumeric characters and symbols</label>\r\n");
      out.write("                    \r\n");
      out.write("                        \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                        <div class=\"wrapper\">\r\n");
      out.write("                    <button type=\"submit\">Login</button> \r\n");
      out.write("                            <br/>\r\n");
      out.write("                    <a href=\"Register.html\">Create Account</a>\r\n");
      out.write("                            <br />\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
