/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-04-30 05:08:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Searchjsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");

System.out.println("inside search jsp");

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<script src=\"search.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>Search Vehicle Details</h1>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<h3>Search by Branch</h3>\r\n");
      out.write("\t\t\t\t<select id=\"sbranch\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t<option value=\"A11\">A11</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"A12\">A12</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"A13\">A13</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"A14\">A14</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"A15\">A15</option>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<form action=\"SearchBranchData.jsp\" onsubmit=\"return searchbranch()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"search\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"branch\" name=\"branch\" value=\"\">\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h1>...OR....</h1>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h3>Search by Vehicle type</h3>\r\n");
      out.write("\t\t\t\t<select id=\"svehicle\">\t\r\n");
      out.write("\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t<option value=\"two wheeler\">Two wheeler</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"four wheeler\">Four wheeler</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<form action=\"SearchVehicleTypeData.jsp\" onsubmit=\"return searchvehicletype()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"search\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"vehicletype\" name=\"vehicletype\" value=\"\">\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h1>...OR....</h1>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h3>Search by Insurance Expiry Month</h3>\r\n");
      out.write("\t\t\t\t<select id=\"Ivehicle\">\t\r\n");
      out.write("\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">January</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">February</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">March</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">April</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">May</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">June</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"6\">July</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"7\">August</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"8\">September</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"9\">October</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10\">November</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"11\">December</option>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<!--  -->\r\n");
      out.write("\t\t\t\t<form action=\"SearchInsuranceDate.jsp\" onsubmit=\"return searchInsuranceDate()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"search\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"insurancedate\" name=\"insurancedate\" value=\"\">\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h1>...OR....</h1>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<h3>Search by Service Due Month</h3>\r\n");
      out.write("\t\t\t\t<select id=\"Servehicle\">\t\r\n");
      out.write("\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t<option value=\"0\">January</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"1\">February</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"2\">March</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"3\">April</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"4\">May</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"5\">June</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"6\">July</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"7\">August</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"8\">September</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"9\">October</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"10\">November</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"11\">December</option>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t<!--  -->\r\n");
      out.write("\t\t\t\t<form action=\"SearchServiceDate.jsp\" onsubmit=\"return searchServiceDate()\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"search\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"servicedate\" name=\"servicedate\" value=\"\">\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
