/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-05-07 09:54:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UpdateAgain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


response.setHeader("Cache-Control","no-cache,no-store,must-revalidate");//HTTP 1.1
response.setHeader("Pragma","no-cache"); //HTTP 1.0
response.setDateHeader ("Expires", 0); //prevents caching at the proxy server

System.out.println("Session Attribute ID: "+request.getSession().getAttribute("Id")+"\n");

if (request.getSession().getAttribute("Id") == "-1") 
{   
       System.out.println("Login Error. Redirecting");
       
       request.getSession().setAttribute("Id","-2");
     response.sendRedirect("Login.jsp");
     return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <link rel=\"icon\" href=\"Capture5.PNG\" type=\"image/gif\" sizes=\"70x70\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("        <link rel='shortcut icon' type='image/x-icon' href='favicon.ico'/>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Update Vehicle Details</title>\r\n");
      out.write("   ");

	String vehicleno=(String)request.getAttribute("vehicleno");
  

      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"UpdatePageValidation.js\"></script>\r\n");
      out.write("        <link rel='stylesheet' type=\"text/css\" href=\"UpdateVehicleInfo.css\">\r\n");
      out.write("\t\t<link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("           \r\n");
      out.write("<!-- Navbar (sit on top) -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"w3-top\">\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"w3-bar w3-white w3-card\" id=\"myNavbar\">\r\n");
      out.write("    \r\n");
      out.write("<a href=\"h1.html\" class=\"w3-bar-item w3-button w3-wide\">\r\n");
      out.write("        \r\n");
      out.write("<div class=\"logo-image\">\r\n");
      out.write("            \r\n");
      out.write("<img src=\"Capture1.PNG\" >\r\n");
      out.write("      \r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("</a>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<div class=\"w3-right w3-hide-small\">\r\n");
      out.write("      \r\n");
      out.write("<a href=\"h1.html\" class=\"w3-bar-item w3-button\">HOME</a>\r\n");
      out.write("      \r\n");
      out.write("<a href=\"aboutus.html\" class=\"w3-bar-item w3-button\">ABOUT US</a>\r\n");
      out.write("     \r\n");
      out.write("<a href=\"contactus.html\" class=\"w3-bar-item w3-button\">CONTACT US</a>\r\n");
      out.write("      \r\n");
      out.write("<form action=\"logout.jsp\" class=\"w3-bar-item w3-button\">\r\n");
      out.write("<button type=\"Logout\" name=\"Logout\" class=\"ll\">Logout</button>\r\n");
      out.write("      </form>\r\n");
      out.write("      \r\n");
      out.write("<!--<a href=\"#contact\" class=\"w3-bar-item w3-button\">\r\n");
      out.write("<i class=\"fa fa-envelope\"></i> CONTACT</a>-->\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("                <br />\r\n");
      out.write("                <div class=\"registration\"><br>\r\n");
      out.write("\r\n");
      out.write("                    <form  align=\"left\" action=\"UpdateformServlet2\" onsubmit=\"return Validate()\" method=\"Post\">\r\n");
      out.write("                    <br><h1 align=\"center\">Update Vehicle Details<br></h1><br>\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"number\">1</span> Vehicle Number\r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"text\" name=\"vehicleno\" id=\"vehicleno\" placeholder=\"Enter Vehicle Number\" required> \r\n");
      out.write("                    <label id=\"lvehicleno\" style=\"color:grey; visibility:visible\">Alphanumeric with max 10 characters</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<span class=\"number\">2</span> Branch\r\n");
      out.write("                    <select name=\"branch\" id=\"userv\" placeholder=\"Enter Branch\" onchange=\"userVehicle()\" required>\r\n");
      out.write("                        <option value=\"\"></option>\r\n");
      out.write("                        <option name=\"A11\">A11</option>\r\n");
      out.write("                        <option name=\"A11\">A12</option>\r\n");
      out.write("                        <option name=\"A11\">A13</option>\r\n");
      out.write("                        <option name=\"A11\">A14</option>\r\n");
      out.write("                        <option name=\"A11\">A15</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"hidden\" name=\"branch\" value=\"\" id=\"branch\">\r\n");
      out.write("                    <label id=\"lbranch\" style=\"color:grey; visibility:visible\">Select one option</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"number\">3</span> Vehicle Type\r\n");
      out.write("                    <select name =\"vehicletype\" id=\"userv\" placeholder=\"Enter Vehicle Type\" onchange=\"userVehicle()\" required>\r\n");
      out.write("                        <option value=\"\"></option>\r\n");
      out.write("                        <option name=\"two Wheeler\">two Wheeler</option>\r\n");
      out.write("                        <option name=\"four Wheeler\">four Wheeler</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"hidden\" name=\"vehicletype\" value=\"\" id=\"vehicletype\">\r\n");
      out.write("                    <label id=\"lvehicletype\" style=\"color:grey; visibility:visible\">Select one option</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"number\">4</span> Insurance Expiry\r\n");
      out.write("                    <input type=\"date\" name=\"insuranceexpirydate\" id=\"insuranceexpirydate\" placeholder=\"MM-DD-YYYY\" onblur=\"insuranceexpirydateonblur()\" required>\r\n");
      out.write("                    <label id=\"linsuranceexpirydate\" style=\"color:grey; visibility:visible\">Enter Insurance Expiry Date(MM-DD-YYYY)</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<span class=\"number\">5</span> Last Service\r\n");
      out.write("                    <input type=\"date\" name=\"lastservicedate\" id=\"lastservicedate\" placeholder=\"MM-DD-YYYY\" onblur=\"lastservicedateonblur()\" required>\r\n");
      out.write("                    <label id=\"llastservicedate\" style=\"color:grey; visibility:visible\">Enter Last Serviced Date(MM-DD-YYYY)</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                    <span class=\"number\">6</span> Service Due\r\n");
      out.write("                    <input type=\"date\" name=\"serviceduedate\" id=\"serviceduedate\" placeholder=\"MM-DD-YYYY\" onblur=\"serviceduedateonblur()\" required>\r\n");
      out.write("                    <label id=\"lserviceduedate\" style=\"color:grey; visibility:visible\">Enter Service Due Date(MM-DD-YYYY)</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                        <div class=\"wrapper\">\r\n");
      out.write("                    <button type=\"submit\" class = \"op\">Register</button> \r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
