/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2019-04-30 08:46:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Updateform2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("  <title>Vehicle Update form</title>\r\n");
      out.write("\r\n");
      out.write("        <script type=\"text/javascript\" src=\"vehicleinfo11.js\"></script>\r\n");
      out.write("        <link rel='stylesheet' type=\"text/css\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t                <h1 align=\"center\">Vehicle Updation Form <br></h1>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"registration\">\r\n");
      out.write("\r\n");
      out.write("                    <form align=\"center\" action=\"UpdateformServlet2\" onsubmit=\"return Validate()\" method=\"Post\">   \r\n");
      out.write("                    VehicleNo<input type=\"text\" name=\"vehicleno\" id=\"vehicleno\" placeholder=\"Enter Vehicle No \" onblur=\"vehiclenoonblur()\" required> \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t   Branch<select id=\"userb\" onchange=\"userbranch()\">\r\n");
      out.write("                    \t<option value=\"\"></option>\r\n");
      out.write("                    \t<option value=\"A11\">A11</option>\r\n");
      out.write("                    \t<option value=\"A12\">A12</option>\r\n");
      out.write("                    \t<option value=\"A13\">A13</option>\r\n");
      out.write("                    \t<option value=\"A14\">A14</option>\r\n");
      out.write("                    \t<option value=\"A15\">A15</option>      \t\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"hidden\" name=\"branch\" value=\"\" id=\"branch\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                    <!-- <input type=\"text\" name=\"branch\" id=\"branch\" placeholder=\"Enter Branch\" onblur=\"branchonblur()\" required>\r\n");
      out.write("                    <label id=\"lbranch\" style=\"color:grey; visibility:visible\">Alphabetic with max 5 characters</label>\r\n");
      out.write("                     -->\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    \r\n");
      out.write("                       Vehicle Type<select id=\"userv\" onchange=\"userVehicle()\">\r\n");
      out.write("                    \t<option value=\"\"></option>\r\n");
      out.write("                    \t<option value=\"two wheeler\">Two wheeler</option>\r\n");
      out.write("                    \t<option value=\"four wheeler\">four wheeler</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"hidden\" name=\"vehicletype\" value=\"\" id=\"vehicletype\">\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t<!-- \r\n");
      out.write("                    <input type=\"text\" name=\"vehicletype\" id=\"vehicletype\" placeholder=\"Enter Vehicle Type\" onblur=\"vehicletypeonblur()\" required>\r\n");
      out.write("                    <label id=\"lvehicletype\" style=\"color:grey; visibility:visible\">Alphabetic with max 15 characters</label>\r\n");
      out.write("                     -->\r\n");
      out.write("                     \r\n");
      out.write("                     \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <input type=\"date\" name=\"insuranceexpirydate\" id=\"insuranceexpirydate\" placeholder=\"MM-DD-YYYY\" onblur=\"insuranceexpirydateonblur()\" required>\r\n");
      out.write("                    <label id=\"linsuranceexpirydate\" style=\"color:grey; visibility:visible\">Enter Insurance Expiry Date(MM-DD-YYYY)</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("\r\n");
      out.write("                    <input type=\"date\" name=\"lastservicedate\" id=\"lastservicedate\" placeholder=\"MM-DD-YYYY\" onblur=\"lastservicedateonblur()\" required>\r\n");
      out.write("                    <label id=\"llastservicedate\" style=\"color:grey; visibility:visible\">Enter Last Serviced Date(MM-DD-YYYY)</label>\r\n");
      out.write("                    \r\n");
      out.write("                   <br>\r\n");
      out.write("                   <br>\r\n");
      out.write("                   \r\n");
      out.write("                   <input type=\"date\" name=\"serviceduedate\" id=\"serviceduedate\" placeholder=\"MM-DD-YYYY\" onblur=\"serviceduedateonblur()\" required>\r\n");
      out.write("                   <label id=\"lserviceduedate\" style=\"color:grey; visibility:visible\">Enter Service Due Date(MM-DD-YYYY)</label>\r\n");
      out.write("                    \r\n");
      out.write("                   <br>\r\n");
      out.write("                   <br>\r\n");
      out.write("                    <input type=\"submit\" value=\"submit\"> \r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
